# Generated by Django 4.1.1 on 2023-01-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.CharField(default='', max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('underheading', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
