# Generated by Django 4.1.1 on 2023-01-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='Blogs',
        ),
    ]
